## Упражнения по библиотеке Numpy

In [7]:
import numpy as np


**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [124]:
arr=np.random.randint(0,15,10)
print(arr)
arr[(arr>=3)&(arr<=8)]=-arr[(arr>=3)&(arr<=8)]
print(arr)

[12  1 13 12  5  5  4  5  6 12]
[12  1 13 12 -5 -5 -4 -5 -6 12]


**2.** Заменить максимальный элемент случайного массива на 0

In [36]:
arr=np.random.randint(0,15,10)
print(arr)
arr[arr==arr.max()]=0
print(arr)

[ 7  8 10  3 10  8  6  9  2 11]
[ 7  8 10  3 10  8  6  9  2  0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [39]:
arr1=np.random.randint(0,10,(2,10))
print(arr1)
arr1[0,:] * arr1[1,:]


[[2 9 0 0 5 3 3 2 4 2]
 [9 9 3 9 5 4 4 1 7 5]]


array([18, 81,  0,  0, 25, 12, 12,  2, 28, 10])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [78]:
arra=np.random.randint(0,5,(8,3))
print(arra)
arrb=np.random.randint(0,5,(2,2))
arrb=arrb.flatten()
print(arrb)
for i in range(8):
    if arra[i,0] in arrb and arra[i,1] in arrb and arra[i,2] in arrb:
        print(arra[i,:])

[[1 2 2]
 [3 4 1]
 [2 1 1]
 [3 4 3]
 [0 1 2]
 [2 0 2]
 [2 4 3]
 [2 0 1]]
[2 2 4 1]
[1 2 2]
[2 1 1]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [136]:
arr=np.random.randint(0,2,(10,3))
print(arr)
print(arr[(arr[:,0]!=arr[:,1])|(arr[:,0]!=arr[:,2])])

[[0 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 1]
 [0 0 1]]
[[0 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [0 0 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [132]:
arr=np.random.randint(0,2,(10,2))
print(arr)
print(arr[(arr[:,0])!=(arr[:,1])])


[[0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]]
[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [143]:
x=np.random.randint(0,4,(4,3))
a=x.diagonal()
b=a[a!=0]
print(np.multiply.reduce(b))

[2 1 0]
2


In [176]:
x=list([[1, 0, 2], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
y=[]
y.append(x[0][0])
y.append(x[1][1])
y.append(x[2][2])
print(y)
z=1
for i in range(3):
    if y[i]!=0:
        z*=y[i]
print(z)

[1, 0, 3]
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [183]:
arr1=np.random.randint(1,4,4)
print(arr1)
arr2=np.random.randint(1,4,4)
print(arr2)
np.prod(arr1)==np.prod(arr2)

[2 3 3 3]
[2 1 3 3]


False

In [186]:
x=[2, 3, 3, 3]
y=[2, 1, 3, 3]
def multiply(lst):
    a = 1
    for i in lst:
        a *= i
    return a
multiply(x)==multiply(y)

False

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [219]:
arr=np.random.randint(0,5,10)
print(arr)
zero = arr==0
arr[1:][zero[:-1]].max()

[1 2 0 3 2 1 3 3 1 2]


3

In [207]:
a=[2, 3, 0, 2, 0,3, 3, 1, 3, 4]
b=[]
for i in range(len(a)-1):
    if a[i]==0:
        b.append(a[i+1])
print(max(b))

3


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [197]:
arr=np.random.randint(0,3,10)
print(arr)
print(np.unique(arr,return_counts=True))

[1 1 2 2 2 2 0 2 1 2]
(array([0, 1, 2]), array([1, 3, 6], dtype=int64))


In [205]:
a=[1, 1, 2, 2, 2, 2, 0, 2, 1, 2]
b=[]
c=[]
for i in range(len(a)):
    if a[i] not in b:
        b.append(a[i])
print(b)
counter=0
for u in range(len(b)):
    for q in range(len(a)):
        if b[u] == a[q]:
            counter+=1
    c.append(counter)
    counter=0
print(c)

[1, 2, 0]
[3, 6, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [209]:
x=np.random.randint(1,3,3)
print(x)
y=np.random.randint(0,3,3)
print(y)
distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip(x, y)))
print(distance)

[2 2 2]
[0 1 0]
3.0


In [212]:
x=[2, 2, 2]
y=[0, 1, 0]

print(((x[0]-y[0])**2+(x[1]-y[1])**2+(x[2]-y[2])**2)**0.5)

3.0


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [55]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [57]:
average_calories=calorie_stats.mean()
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [59]:
calorie_stats_sorted=np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [60]:
median_calories=np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [67]:
nth_percentile1=np.percentile(calorie_stats,100)
print(nth_percentile1)
nth_percentile2=np.percentile(calorie_stats,50)
print(nth_percentile2)
nth_percentile3=np.percentile(calorie_stats,1)
print(nth_percentile3)
nth_percentile=np.percentile(calorie_stats,4)
print(nth_percentile)

160.0
110.0
50.0
70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [193]:
a=len(calorie_stats[calorie_stats>60])
b=len(calorie_stats)
more_calories=round(a/b*100)
print(more_calories)

96


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [68]:
calorie_std=np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Стандартное отклонение используется для измерения отклонения набора данных относительно среднего значения.
Mycrunch могут использовать это для того что бы показать покупателям как сильно отличается 
количество каллорий в CrunchieMunchies в отличии от конкурентов на рынке.
